### ISSUE TITLE
您好，导入项目运行报错，No such file or directory: 'model_saved/tokenizer.pickle'，谢谢

### ISSUE THREAD

**Issue by luoqigong** [CarryChang/Customer_Satisfaction_Analysis#5]
Traceback (most recent call last):
  File "Project_Main.py", line 48, in <module>
    model_train()
  File "D:\python3.7.8\爬虫\民宿评论分析\Customer_Satisfaction_Analysis-master\s
a_model_train.py", line 18, in model_train
    model.train(train_data, label, num_classes=2, batch_size=256, epochs=2, verb
ose=1, evaluate=True)
  File "D:\python3.7.8\lib\site-packages\litNlp\train.py", line 41, in train
    tokenizer = self.train_tk(train_data)
  File "D:\python3.7.8\lib\site-packages\litNlp\train.py", line 32, in train_tk
    with open(self.tokenize_path, 'wb') as tokenize:
FileNotFoundError: [Errno 2] No such file or directory: 'model_saved/tokenizer.p
ickle'
请问少了什么吗，怎么解决？谢谢

**Comment by CarryChang** [comment]
有一个文件夹需要新建，现在重新 fork 一下项目，可以直接运行了
